/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as PrecoChatbotRouteImport } from './routes/preco-chatbot'
import { Route as PostupRouteImport } from './routes/postup'
import { Route as OchranaUdajovRouteImport } from './routes/ochrana-udajov'
import { Route as NavrhRouteImport } from './routes/navrh'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FarbyRouteImport } from './routes/farby'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjektyIndexRouteImport } from './routes/projekty.index'
import { Route as ProjektySlugRouteImport } from './routes/projekty.$slug'

const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecoChatbotRoute = PrecoChatbotRouteImport.update({
  id: '/preco-chatbot',
  path: '/preco-chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const PostupRoute = PostupRouteImport.update({
  id: '/postup',
  path: '/postup',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaUdajovRoute = OchranaUdajovRouteImport.update({
  id: '/ochrana-udajov',
  path: '/ochrana-udajov',
  getParentRoute: () => rootRouteImport,
} as any)
const NavrhRoute = NavrhRouteImport.update({
  id: '/navrh',
  path: '/navrh',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FarbyRoute = FarbyRouteImport.update({
  id: '/farby',
  path: '/farby',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektyIndexRoute = ProjektyIndexRouteImport.update({
  id: '/projekty/',
  path: '/projekty/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektySlugRoute = ProjektySlugRouteImport.update({
  id: '/projekty/$slug',
  path: '/projekty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/cookies': typeof CookiesRoute
  '/farby': typeof FarbyRoute
  '/kontakt': typeof KontaktRoute
  '/navrh': typeof NavrhRoute
  '/ochrana-udajov': typeof OchranaUdajovRoute
  '/postup': typeof PostupRoute
  '/preco-chatbot': typeof PrecoChatbotRoute
  '/sluzby': typeof SluzbyRoute
  '/projekty/$slug': typeof ProjektySlugRoute
  '/projekty/': typeof ProjektyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/cookies': typeof CookiesRoute
  '/farby': typeof FarbyRoute
  '/kontakt': typeof KontaktRoute
  '/navrh': typeof NavrhRoute
  '/ochrana-udajov': typeof OchranaUdajovRoute
  '/postup': typeof PostupRoute
  '/preco-chatbot': typeof PrecoChatbotRoute
  '/sluzby': typeof SluzbyRoute
  '/projekty/$slug': typeof ProjektySlugRoute
  '/projekty': typeof ProjektyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/cookies': typeof CookiesRoute
  '/farby': typeof FarbyRoute
  '/kontakt': typeof KontaktRoute
  '/navrh': typeof NavrhRoute
  '/ochrana-udajov': typeof OchranaUdajovRoute
  '/postup': typeof PostupRoute
  '/preco-chatbot': typeof PrecoChatbotRoute
  '/sluzby': typeof SluzbyRoute
  '/projekty/$slug': typeof ProjektySlugRoute
  '/projekty/': typeof ProjektyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cennik'
    | '/cookies'
    | '/farby'
    | '/kontakt'
    | '/navrh'
    | '/ochrana-udajov'
    | '/postup'
    | '/preco-chatbot'
    | '/sluzby'
    | '/projekty/$slug'
    | '/projekty/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cennik'
    | '/cookies'
    | '/farby'
    | '/kontakt'
    | '/navrh'
    | '/ochrana-udajov'
    | '/postup'
    | '/preco-chatbot'
    | '/sluzby'
    | '/projekty/$slug'
    | '/projekty'
  id:
    | '__root__'
    | '/'
    | '/cennik'
    | '/cookies'
    | '/farby'
    | '/kontakt'
    | '/navrh'
    | '/ochrana-udajov'
    | '/postup'
    | '/preco-chatbot'
    | '/sluzby'
    | '/projekty/$slug'
    | '/projekty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CennikRoute: typeof CennikRoute
  CookiesRoute: typeof CookiesRoute
  FarbyRoute: typeof FarbyRoute
  KontaktRoute: typeof KontaktRoute
  NavrhRoute: typeof NavrhRoute
  OchranaUdajovRoute: typeof OchranaUdajovRoute
  PostupRoute: typeof PostupRoute
  PrecoChatbotRoute: typeof PrecoChatbotRoute
  SluzbyRoute: typeof SluzbyRoute
  ProjektySlugRoute: typeof ProjektySlugRoute
  ProjektyIndexRoute: typeof ProjektyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preco-chatbot': {
      id: '/preco-chatbot'
      path: '/preco-chatbot'
      fullPath: '/preco-chatbot'
      preLoaderRoute: typeof PrecoChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postup': {
      id: '/postup'
      path: '/postup'
      fullPath: '/postup'
      preLoaderRoute: typeof PostupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-udajov': {
      id: '/ochrana-udajov'
      path: '/ochrana-udajov'
      fullPath: '/ochrana-udajov'
      preLoaderRoute: typeof OchranaUdajovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navrh': {
      id: '/navrh'
      path: '/navrh'
      fullPath: '/navrh'
      preLoaderRoute: typeof NavrhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farby': {
      id: '/farby'
      path: '/farby'
      fullPath: '/farby'
      preLoaderRoute: typeof FarbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekty/': {
      id: '/projekty/'
      path: '/projekty'
      fullPath: '/projekty/'
      preLoaderRoute: typeof ProjektyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekty/$slug': {
      id: '/projekty/$slug'
      path: '/projekty/$slug'
      fullPath: '/projekty/$slug'
      preLoaderRoute: typeof ProjektySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CennikRoute: CennikRoute,
  CookiesRoute: CookiesRoute,
  FarbyRoute: FarbyRoute,
  KontaktRoute: KontaktRoute,
  NavrhRoute: NavrhRoute,
  OchranaUdajovRoute: OchranaUdajovRoute,
  PostupRoute: PostupRoute,
  PrecoChatbotRoute: PrecoChatbotRoute,
  SluzbyRoute: SluzbyRoute,
  ProjektySlugRoute: ProjektySlugRoute,
  ProjektyIndexRoute: ProjektyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
