/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as PostupRouteImport } from './routes/postup'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FarbyRouteImport } from './routes/farby'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjektyIndexRouteImport } from './routes/projekty.index'
import { Route as ProjektySlugRouteImport } from './routes/projekty.$slug'

const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const PostupRoute = PostupRouteImport.update({
  id: '/postup',
  path: '/postup',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FarbyRoute = FarbyRouteImport.update({
  id: '/farby',
  path: '/farby',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektyIndexRoute = ProjektyIndexRouteImport.update({
  id: '/projekty/',
  path: '/projekty/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektySlugRoute = ProjektySlugRouteImport.update({
  id: '/projekty/$slug',
  path: '/projekty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farby': typeof FarbyRoute
  '/kontakt': typeof KontaktRoute
  '/postup': typeof PostupRoute
  '/sluzby': typeof SluzbyRoute
  '/projekty/$slug': typeof ProjektySlugRoute
  '/projekty/': typeof ProjektyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/farby': typeof FarbyRoute
  '/kontakt': typeof KontaktRoute
  '/postup': typeof PostupRoute
  '/sluzby': typeof SluzbyRoute
  '/projekty/$slug': typeof ProjektySlugRoute
  '/projekty': typeof ProjektyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farby': typeof FarbyRoute
  '/kontakt': typeof KontaktRoute
  '/postup': typeof PostupRoute
  '/sluzby': typeof SluzbyRoute
  '/projekty/$slug': typeof ProjektySlugRoute
  '/projekty/': typeof ProjektyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/farby'
    | '/kontakt'
    | '/postup'
    | '/sluzby'
    | '/projekty/$slug'
    | '/projekty/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/farby'
    | '/kontakt'
    | '/postup'
    | '/sluzby'
    | '/projekty/$slug'
    | '/projekty'
  id:
    | '__root__'
    | '/'
    | '/farby'
    | '/kontakt'
    | '/postup'
    | '/sluzby'
    | '/projekty/$slug'
    | '/projekty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarbyRoute: typeof FarbyRoute
  KontaktRoute: typeof KontaktRoute
  PostupRoute: typeof PostupRoute
  SluzbyRoute: typeof SluzbyRoute
  ProjektySlugRoute: typeof ProjektySlugRoute
  ProjektyIndexRoute: typeof ProjektyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postup': {
      id: '/postup'
      path: '/postup'
      fullPath: '/postup'
      preLoaderRoute: typeof PostupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farby': {
      id: '/farby'
      path: '/farby'
      fullPath: '/farby'
      preLoaderRoute: typeof FarbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekty/': {
      id: '/projekty/'
      path: '/projekty'
      fullPath: '/projekty/'
      preLoaderRoute: typeof ProjektyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekty/$slug': {
      id: '/projekty/$slug'
      path: '/projekty/$slug'
      fullPath: '/projekty/$slug'
      preLoaderRoute: typeof ProjektySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarbyRoute: FarbyRoute,
  KontaktRoute: KontaktRoute,
  PostupRoute: PostupRoute,
  SluzbyRoute: SluzbyRoute,
  ProjektySlugRoute: ProjektySlugRoute,
  ProjektyIndexRoute: ProjektyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
